[package]
name = "space_cake"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
rand = "0.8.5"
crossterm = "0.25.0"
ggez = "0.9"
glam = { version = "0.24", features = ["rand"] }  # Vector math library